### ISSUE TITLE
能否提供下 全的依赖

### ISSUE THREAD

**Issue by TheheiWorld** [ctripcorp/C-OCR#3]
com.ctrip.basebiz 这个都没有提供

**Comment by zhouyuan2016** [comment]
你好，

具体缺少什么依赖？

现在是要跑起来，看下效果吗


Thanks,
Nathan Zhou,
16193

发件人: TheheiWorld <notifications@github.com>
发送时间: 2019年7月30日 13:04
收件人: ctripcorp/C-OCR <C-OCR@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [External][ctripcorp/C-OCR] 能否提供下 全的依赖 (#3)


com.ctrip.basebiz 这个都没有提供

**Comment by TheheiWorld** [comment]
![image](https://user-images.githubusercontent.com/22994746/62107774-e79dbd80-b2da-11e9-9177-cb5e81d3506c.png)

**Comment by zhouyuan2016** [comment]
在最外层有个pom文件，如附件


Thanks,
Nathan Zhou,
16193

发件人: TheheiWorld <notifications@github.com>
发送时间: 2019年7月30日 15:02
收件人: ctripcorp/C-OCR <C-OCR@noreply.github.com>
抄送: zy周源 <zhouyuan@Ctrip.com>; Comment <comment@noreply.github.com>
主题: [External]Re: [ctripcorp/C-OCR] 能否提供下 全的依赖 (#3)


[图像已被发件人删除。 image]<https://user-images.githubusercontent.com/22994746/62107774-e79dbd80-b2da-11e9-9177-cb5e81d3506c.png>

**Comment by TheheiWorld** [comment]
![image](https://user-images.githubusercontent.com/22994746/62108296-4ca5e300-b2dc-11e9-918b-9d042c042fc3.png)
### 这个是clone下来的项目结构，最外层的pom并没有提供

**Comment by TheheiWorld** [comment]
@zhouyuan2016 我自己改comon 及其他项目的 pom吧 最外层没有就算了

**Comment by guanbo123456** [comment]
项目怎么能跑起来，看下效果？

**Comment by lestchun** [comment]
``` xml  
<?xml version="1.0" encoding="UTF-8"?>
<project  xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
    <packaging>pom</packaging>
    <modules>
	<module>Common</module>
	<module>Detection</module>
	<module>PostProcessing</module>
	<module>RefuseRecognition</module>
    </modules>
	<artifactId>COCR</artifactId>
        <groupId>com.ctrip.basebiz</groupId>
        <version>1.0.0</version>

	<properties>
		<java.version>1.8</java.version>
	</properties>
</project>

````
自己在最外面添加个这个不就好了嘛
